# templates/02_post-install-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-post-install-hook
  annotations:
    # 🎯 THIS IS WHERE THE HOOK ANNOTATION GOES
    "helm.sh/hook": post-install
    # Ensure the Job is deleted after it succeeds
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: verify-nginx-service
        image: busybox:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "--- Starting Post-Install Verification ---"
            # Wait for the NGINX service endpoint to be ready
            sleep 5
            # In a real-world scenario, you would use an image with 'curl'
            # to check the actual service endpoint (e.g., curl nginx-service)
            echo "Successfully deployed NGINX Deployment and Service 'nginx-service'."
            echo "Post-install hook finished successfully."
      restartPolicy: OnFailure
  backoffLimit: 4
