# templates/02_clusterrole-hook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-viewer-role
  annotations:
    # 🎯 The essential annotation: Runs after the main deployment phase
    "helm.sh/resource-policy": "keep"
    "meta.helm.sh/release-name": hooks-missing
    "meta.helm.sh/release-namespace": nginx-hook-test01
  labels:
    app: nginx
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
